GET http://localhost:3001/api/persons

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Sample Person",
    "number": "123-890",
}

###
DELETE http://localhost:3001/api/persons/3